### ISSUE TITLE
Default to localhost

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/sdk-doctor#1]
If running sdk-doctor diagnose, it'd be nice if it warned and assumed couchbase://localhost

**Comment by brett19** [comment]
The main reason I did not do this is that running diagnostic on the localhost cluster isn't very useful, since the majority of the testing is network related.

**Comment by ingenthr** [comment]
I agree, but some use cases like the Mac OS Sierra (where query fails to run and just crashes all the time) or Docker (where people forget to map ports) are localhost.  I'm okay if you don't want to do this, but I do kind of like the symmetry with the sdks of 'localhost by default if not specified'.

Up to you, close it if you decide not to.

**Comment by ingenthr** [comment]
Oh, Windows anniv. edition also has that "some services fail to run" thing.
