### ISSUE TITLE
Configuration is not logged on Windows

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/sdk-doctor#10]
As discovered in https://issues.couchbase.com/browse/JCBC-1050, for some reason the configuration isn't logged on Windows when it seems to be retrieved.  See the comments and the log attachment there.

**Comment by brett19** [comment]
Hey Matt,
This is actually an issue with the environment.  There is not any platform-specific code within the doctor.  I suspect based on the ticket that Docker on Windows has wierd networking configurations making it impossible to fetch the configuration.
Cheers, Brett
