### ISSUE TITLE
Complex Password not parsed properly

### ISSUE THREAD

**Issue by AlbertoBonfiglio** [couchbaselabs/sdk-doctor#13]
Hello,
running a diagnostic against a bucket secured with a password containing special characters (e.g. ! or !!) does not work and gives a invalid bucket name/password error.

**Comment by brett19** [comment]
Hey @AlbertoBonfiglio ,
Are you appropriately escaping the password on the terminal?
Cheers, Brett

**Comment by AlbertoBonfiglio** [comment]
Doh!! No I wasn't... LOL still new at this linux console stuff...
