### ISSUE TITLE
sdk-doctor may not handle situation where non-KV nodes are first

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/sdk-doctor#26]
Environment: Couchbase Cloud with 6 KV nodes, 4 nodes with other services.

https://gist.github.com/ingenthr/e3f37b8c0509c5a4bf41fa4168642dd0

**Comment by brett19** [comment]
This is actually not a bug, it looks like the environment is incorrectly rejecting connections to memcached on non-KV nodes.  This is an error and points to a bug in the firewall configuration or routing as opposed to a bug in sdk-doctor.
